{% set name = "pylyzer" %}
{% set version = "0.0.31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pylyzer-{{ version }}.tar.gz
  sha256: 55f52796e4220c09f66177043a63d30a50ae9a21d0d96ad1b1f6ba4a0566298e

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - rust >=1.66
  host:
    - python
    - maturin >=0.12
    - pip
  run:
    - python

test:
  commands:
    - pip check
    - pylyzer -h
  requires:
    - pip

about:
  home: https://github.com/mtshiba/pylyzer
  summary: A fast static code analyzer & language server for Python
  license: MIT
  license_file:
    - LICENSE
    - extension/LICENSE

extra:
  recipe-maintainers:
    - thewchan
