{% set name = "pylyzer" %}
{% set version = "0.0.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pylyzer-{{ version }}.tar.gz
  sha256: 7ea08a36c6595e12f6d6f2f8045af976aacce352e8f269df0f8d3f45f3f78862

build:
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - rust >=1.66
  host:
    - python
    - maturin >=0.12
    - pip
  run:
    - python

test:
  commands:
    - pip check
    - pylyzer -h
  requires:
    - pip

about:
  home: https://github.com/mtshiba/pylyzer
  summary: A fast static code analyzer & language server for Python
  license: MIT
  license_file:
    - LICENSE
    - extension/LICENSE

extra:
  recipe-maintainers:
    - thewchan
