{% set name = "pylyzer" %}
{% set version = "0.0.39" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pylyzer-{{ version }}.tar.gz
  sha256: 430674744cb30735d0dae3666f7a36b9bd5904f7b60f7f255d5549ebe91481c1

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - rust >=1.66
  host:
    - python
    - maturin >=0.12
    - pip
  run:
    - python

test:
  commands:
    - pip check
    - pylyzer -h
  requires:
    - pip

about:
  home: https://github.com/mtshiba/pylyzer
  summary: A fast static code analyzer & language server for Python
  license: MIT
  license_file:
    - LICENSE
    - extension/LICENSE

extra:
  recipe-maintainers:
    - thewchan
