{% set name = "pylyzer" %}
{% set version = "0.0.78" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mtshiba/pylyzer/archive/v{{ version }}.tar.gz
  sha256: a9ffaa881f9d40b64ee36b8c93f59d1b0f4bbc0af57814f611b2bae97d84f876

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - python
    - maturin >=0.12
    - setuptools-rust
    - pip
  run:
    - python

test:
  commands:
    - pip check
    - pylyzer -h
  requires:
    - pip

about:
  home: https://github.com/mtshiba/pylyzer
  summary: A fast static code analyzer & language server for Python
  license: MIT
  license_file:
    - LICENSE
    - extension/LICENSE

extra:
  recipe-maintainers:
    - danielnachun
    - thewchan
